name: Readme - svg text

on:
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.GH_TOKEN }}

    - name: Run the action
      uses: ./
      with:
        input-text: |
          hello, from svg typing.
          This is dyamically generated.
          Hello!

    - name: Commit and push if it changed
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -m "[feat] update readme-typing.svg" || exit 0
        git push origin ${{ github.head_ref }}
        echo "Changes committed and pushed."
